### ISSUE TITLE
Gringotts in combination with UltimateShops Premium and Paper 1.14.3 does not seem to deposit emeralds in an offline players inventory / vault.

### ISSUE THREAD

**Issue by cfi2017** [nikosgram/gringotts#2]
As the title details. The emeralds are simply voided.

**Comment by nikosgram** [comment]
Hello, I have never check Gringotts on Paper software. I'll check it out. There is one more ticket taking about Gringotts on Paper. #3

**Comment by cfi2017** [comment]
If it helps, this seems to work for chest vaults. If a player does not have a chest vault (hence only their inventory / enderchest is counted) it doesn't seem to work.

**Comment by nikosgram** [comment]
Thank you for the details. Can you send me also the list of your plugins installed in your server? I really need that so I can replicate the issue.

**Comment by cfi2017** [comment]
Sure! 

The most important plugins, I'm guessing, are 
- Vault
- UltimateShops (which integrates with Vault)
- AuctionHouse (which integrates with Vault)
- AreaShop (which integrates with Vault)
- EssentialsX
as well as some miscellaneous plugins that shouldn't interact with the economy system. The only other one I could think of would be ProtocolLib.

If you need a full list I can provide that, but those should be the most important. Since they all integrate with vault you should be able to use any economy plugin to replicate the issue though.

We are running Paper 1.14.4 a the moment (build 152 if I recall correctly) and the workaround where every player needs to create a chest vault seems to be working well.

**Comment by nikosgram** [comment]
Thank you @cfi2017. I'll check it out.

**Comment by thboehi** [comment]
Hello. I have the same issue. Also on Paper.

**Comment by nikosgram** [comment]
Hello,

Can you try to replicate the issue on the latest pre-release version of Gringotts please?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-ref98c00

Just remember, this version is for testing purposes only. :)
