### ISSUE TITLE
Ended chest vault not working/ add support for shulkerbox vaults

### ISSUE THREAD

**Issue by matarbuckle** [nikosgram/gringotts#20]
It won’t let me create a vault on an ended chest. I tried changing the name in the configuration file to add an underscore but it didn’t do anything either. There’s no error message when i type [vault] on it, simply nothing happens.
I’d also love to see support for shulkerboxs. It would be nice to not have to have a bunch of vaults, when i could put everything into one place with out there being a limit

**Comment by nikosgram** [comment]
You don't need to have a sign on front of the enderchest to set it up as vault. is automatically doing it as the inventory of the player. Just be sure that you have the enderchest vault enabled in the configuration file.
