### ISSUE TITLE
Disable Crafting - Option [suggestion]

### ISSUE THREAD

**Issue by iomatix** [nikosgram/gringotts#25]
This option would dissallow players to craft/smelt items which are currencies <- but not by material but whole item's meta. 
So eg. if the material has its `displayname` check also this and allow crafting from standard materials.

**Comment by nikosgram** [comment]
That's actually a really good suggestion.

**Comment by Kwikxilver** [comment]
To add to this - the option to disable obtaining currency from mob drops and villager trades would also be great. ie if the currency is Gold, you should be able to turn off Gold Nugget drops and turn off trading emeralds for Gold Ingots. I don't know how easy it is to implement this though.

**Comment by jaz-on** [comment]
>This option would dissallow players to craft/smelt items which are currencies <- but not by material but whole item's meta.
So eg. if the material has its displayname check also this and allow crafting from standard materials.

Of course, you could disallow the crafting/smelt of items used for your economy but I'm not sure it's a good idea to limit or disable features of minecraft. Imho the easiest method is to add NBT tag to the item used as currency on your server. This makes it possible to dissociate the vanilla block (gold_nugget for example) and the block with the tag (I use lore message for example) which cannot be forged or cannot be obtained by a mob farm.

> To add to this - the option to disable obtaining currency from mob drops and villager trades would also be great. ie if the currency is Gold, you should be able to turn off Gold Nugget drops and turn off trading emeralds for Gold Ingots. I don't know how easy it is to implement this though.

Third party plugins can be used to modify entities loots (something like this : https://www.spigotmc.org/resources/custom-drops-editor-1-13-1-16-easy-to-use-hard-not-to-want.71153/). I'm not sure that's Gringott's primary goal.

Items renaming is not part of the plugin whereas it would surely be more important but considered (with reason) as out of scope.
