### ISSUE TITLE
Barrel doesn't work [Issue]

### ISSUE THREAD

**Issue by iomatix** [nikosgram/gringotts#26]
`usevault:
  container: true`
Doesn't affect barrels.

**Comment by nikosgram** [comment]
What's your version of Gringotts?

**Comment by iomatix** [comment]
I was using latest version 1.14.4 on state 6 Dec 2019. Nowadays I'm not developing Minecraft server - sorry I don't remember exact version number. 
Kind Regards!

**Comment by nikosgram** [comment]
Can you try it with the latest pre-release version?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-rbed0924

Thank you. :)

**Comment by Kwikxilver** [comment]
@nikosgram I've just tried this with the latest pre-release, and vault creation works fine with barrels.
