### ISSUE TITLE
Money pay isn't working

### ISSUE THREAD

**Issue by Vimppura** [nikosgram/gringotts#3]
Command /money pay <amount> <player> ain't working. When players use the command to send money to other players, they both recieve message which tells that 0 money has been transfered, even tho the amount has been bigger. And it's not the message that's wrong, because there's really not any money going in either direction. Withdraw and deposit commands seem to work without any problems tho.

This bug appeared after updating the plugin to 2.11.1-SNAPSHOT. We use the latest Vault (1.7.2-b107). Our server in 1.14.3 version (Paper).

**Comment by nikosgram** [comment]
Hello, I haven't test Gringotts on Paper yet.

I know that Paper having some restriction on spigot's events. I'll check it out.

Thank you for the report.

**Comment by viktordimov** [comment]
I can confirm, /money pay does not work on paper. It worked once, not a single time ever since.
