### ISSUE TITLE
Town vaults lose balance on town rename, unable to create new vault

### ISSUE THREAD

**Issue by Kwikxilver** [nikosgram/gringotts#33]
Hi, currently working with the latest snapshot of Gringotts and Towny. A player had created a town vault, but when they renamed their town their vault didn't change town name, and then the balance of gold which was in it disappeared. Further attempts to create new vaults with the updated name did not create.

Let me know if you need any more info - would be great to know what this is. Thanks!

Was getting this error in the console: [Pastebin link](https://pastebin.com/E1PvFvKy)

**Comment by nikosgram** [comment]
Hello @yntel. 

I didn't know you can change the name of the town. I'll have a look on it after work. I just assigned myself into the ticket t investigate it. 

Thank you or taking the time to report the issue. :)

**Comment by ghost** [comment]
@nikosgram there's an event for checking if a town is renamed: [RenameTownEvent](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/event/RenameTownEvent.java)

Once this is called you can get the town from the event and use `event.getOldName()` and `event.getTown().getAccount().getName()` to rename the economy account.

**Comment by nikosgram** [comment]
Progress report: 
![image](https://user-images.githubusercontent.com/3318873/77964808-a5000b00-72d7-11ea-86a1-6dd37aef5904.png)
![image](https://user-images.githubusercontent.com/3318873/77964820-aaf5ec00-72d7-11ea-85fd-ff2d9a746034.png)
![image](https://user-images.githubusercontent.com/3318873/77964825-afbaa000-72d7-11ea-830d-0f704099f676.png)

**Comment by nikosgram** [comment]
Hello, if it's possible, can you verify that the problem got fixed?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-ref98c00

Thank you :)

**Comment by ghost** [comment]
Absolutely!

**Comment by Kwikxilver** [comment]
I can confirm that this has been fixed for both towns and nations, thank you for the fix!
