### ISSUE TITLE
Nation vaults don't bold [Nation Vault] on creation

### ISSUE THREAD

**Issue by Kwikxilver** [nikosgram/gringotts#34]
Using latest snapshot.

This is mostly a cosmetic thing, but Nation Vaults don't bold like other vaults once they're created.

Not a high priority as all other functions seem to work fine, but thought I would point it out.

Thanks!

**Comment by nikosgram** [comment]
Hello @yntel , is that happening only on Nation, or on Town vaults too?

**Comment by Kwikxilver** [comment]
Just Nation vaults. Town vaults bold just fine!

**Comment by nikosgram** [comment]
Hello, if it's possible, can you verify that the problem got fixed?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-ref98c00

Thank you :)

**Comment by Kwikxilver** [comment]
I can confirm this is fixed in that build you linked. Thanks!
