### ISSUE TITLE
bug - Tab-complete errors for /moneyadm

### ISSUE THREAD

**Issue by Kwikxilver** [nikosgram/gringotts#35]
Hi, running the latest snapshot with Paper-149 and encountering an issue when I try and use the /moneyadm commands.

I can type _/moneyadm rm_ or _/moneyadm add_ just fine, but once I continue typing after _add_ or _rm_ I get this message in chat for every additional keystroke -  **"An internal error occurred while attempting to tab-complete this command."** It just continues spamming the chat with this the more I type.

In my console when I get that chat message ingame, I get this error with every keystroke: [https://pastebin.com/XcYvRPFx](https://pastebin.com/XcYvRPFx)

Not sure how to fix this. It doesn't seem to affect the operation of the command, but fills the logs and I'm worried there might be something worse happening under the hood.

Thanks in advance for your help!

**Comment by nikosgram** [comment]
I’m afraid the next pre-release is gonna take some time to be done. I have put a lot of changes on it. 

Though, I fixed the autocompleted issues. 

You can see the progress I have done on my saved livestream from yesterday. 

https://www.youtube.com/watch?v=r6tGSk_5QRg

☺️

**Comment by nikosgram** [comment]
Hello @yntel,

Can you download the latest pre-release version and verify that the problem got fixed?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-rf77e523

Thank you :)
Nikolaos.
