### ISSUE TITLE
Support for CustomItems

### ISSUE THREAD

**Issue by jojodmo** [nikosgram/gringotts#36]
[Tracking] Please add support for [CustomItems](https://polymart.org/resource/custom-items.1/) to be used as materials in Gringotts.

CustomItems API Reference: https://github.com/jojodmo/CustomItems/wiki/Developer-API
CustomItems API Class: https://github.com/jojodmo/CustomItems/blob/master/API/CustomItemsAPI.java

Thank you!

**Comment by foxotic** [comment]
Would really love to see this soon!
