### ISSUE TITLE
Towny / Economy issue - Says cannot afford

### ISSUE THREAD

**Issue by Darklom** [nikosgram/gringotts#37]
THIS is a crosspost with - https://github.com/TownyAdvanced/Towny/issues/3870
Is anyone else having an issue of setting a plot type with it saying "You can't afford this"

I'm using Gringotts with Vault.

The weird part is that.. everything else in the towny economy works.

[NO ERRORS ON CONSOLE]
1.15.2

--

Gringotts Version 2.11.2
Towny latest

**Comment by Curtis73** [comment]
You're not alone - I'm experiencing this too

**Comment by Darklom** [comment]
Thank you for the confirmation Curtis - @nikosgram

**Comment by nikosgram** [comment]
Hello. Thank you for the report. Working on it. ☺️

**Comment by Darklom** [comment]
Thank you nikos!

LlmDI from TownyAdvanced was able to add a work around fix!  @Curtis73  I got it working now

https://github.com/TownyAdvanced/Towny/issues/3870
