### ISSUE TITLE
PlaceholderAPI Incompatibility

### ISSUE THREAD

**Issue by Kwikxilver** [nikosgram/gringotts#40]
Hey again,

Been noticing this popping up every time one of my players checks their Gringotts balance - looks like an incompatibility with PlaceholderAPI (I'm running PlaceholderAPI 2.10.5). This spams the console:

Console Output: [https://pastebin.com/v4rvVdm2](https://pastebin.com/v4rvVdm2)

This has only started happening when I added the latest Gringotts release - it's possible it could be connected to the tab-complete fixes you pushed in that?

Let me know if I need to report this to the PlaceholderAPI dev instead. Thank you!

**Comment by Darklom** [comment]
I also have this same issue throughout the past few months..
