### ISSUE TITLE
Customize items as currency ?

### ISSUE THREAD

**Issue by Aubhisamme** [nikosgram/gringotts#51]
Hello,

By only using a datapack plugin, we have managed to create a new item we want to use as a currency for the server. This is how the server recognises it:
minecraft:emerald{display:{Name:'{"text":"Rubis","italic":false}'},CustomModelData:1}

(CustomModelData:1) is the Ruby texture:
![Ruby](https://user-images.githubusercontent.com/60467502/83035084-505be080-a039-11ea-951d-058ef166bf8a.png)

We can give it to ourselves without any problem. But we can't manage to make Gringotts recognise it as a material. Is it possible and how would you do it?

**Comment by Bossbirdyman51** [comment]
Can i see your config ? It's work when you give Item with meta and say /money ?
