### ISSUE TITLE
Towny Error with fatal syntax error

### ISSUE THREAD

**Issue by GamerMedic** [nikosgram/gringotts#59]
INFO [Gringotts] Enabling Gringotts v2.11.1-SNAPSHOT
29.09 02:53:55 [Server] INFO [Gringotts] Found Bukkit version: 1.16.2-R0.1-SNAPSHOT. All features enabled.
29.09 02:53:55 [Server] WARN [Gringotts] Unable to hook plugin Factions
29.09 02:53:55 [Server] WARN [Gringotts] Unable to load Factions handler because your version of Factions is not compatible with Gringotts. Factions support will not work
29.09 02:53:55 [Server] WARN [Gringotts] Loaded class com.palmergames.bukkit.towny.Towny from Towny v0.96.2.0 which is not a depend, softdepend or loadbefore of this plugin.
29.09 02:53:55 [Server] INFO [Gringotts] Plugin Towny hooked.
29.09 02:53:55 [Server] ERROR Error occurred while enabling Gringotts v2.11.1-SNAPSHOT (Is it up to date?)
29.09 02:53:55 [Server] INFO java.lang.VerifyError: Bad type on operand stack
29.09 02:53:55 [Server] INFO Exception Details:
29.09 02:53:55 [Server] INFO Location:
29.09 02:53:55 [Server] INFO org/gestern/gringotts/dependency/ValidTownyHandler.getNationAccountHolder(Lorg/bukkit/entity/Player;)Lorg/gestern/gringotts/dependency/TownyAccountHolder; @32: invokespecial
29.09 02:53:55 [Server] INFO Reason:
29.09 02:53:55 [Server] INFO Type 'com/palmergames/bukkit/towny/object/Nation' (current frame, stack[2]) is not assignable to 'com/palmergames/bukkit/towny/object/TownyEconomyObject'
29.09 02:53:55 [Server] INFO Current Frame:
29.09 02:53:55 [Server] INFO bci: @32
29.09 02:53:55 [Server] INFO flags: { }
29.09 02:53:55 [Server] INFO locals: { 'org/gestern/gringotts/dependency/ValidTownyHandler', 'org/bukkit/entity/Player', 'com/palmergames/bukkit/towny/object/Resident', 'com/palmergames/bukkit/towny/object/Town', 'com/palmergames/bukkit/towny/object/Nation' }
29.09 02:53:55 [Server] INFO stack: { uninitialized 24, uninitialized 24, 'com/palmergames/bukkit/towny/object/Nation', 'java/lang/String' }
29.09 02:53:55 [Server] INFO Bytecode:
29.09 02:53:55 [Server] Startup 0000000: b800 3c2b b900 4201 00b6 0048 4d2c b600
29.09 02:53:55 [Server] Startup 0000010: 4e4e 2db6 005f 3a04 bb00 5059 1904 120e
29.09 02:53:55 [Server] Startup 0000020: b700 53b0 4d01 b0
29.09 02:53:55 [Server] INFO Exception Handler Table:
29.09 02:53:55 [Server] INFO bci [0, 35] => handler: 36
29.09 02:53:55 [Server] INFO Stackmap Table:
29.09 02:53:55 [Server] INFO same_locals_1_stack_item_frame(@36,Object[#54])
29.09 02:53:55 [Server] INFO at org.gestern.gringotts.dependency.TownyHandler.getTownyHandler(TownyHandler.java:31) ~[?:?]
29.09 02:53:55 [Server] INFO at org.gestern.gringotts.dependency.Dependency.<init>(Dependency.java:39) ~[?:?]
29.09 02:53:55 [Server] INFO at org.gestern.gringotts.dependency.Dependency.<clinit>(Dependency.java:22) ~[?:?]
29.09 02:53:55 [Server] INFO at org.gestern.gringotts.Gringotts.registerEconomy(Gringotts.java:172) ~[?:?]
29.09 02:53:55 [Server] INFO at org.gestern.gringotts.Gringotts.onEnable(Gringotts.java:110) ~[?:?]
29.09 02:53:55 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
29.09 02:53:55 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:?]

-- The config.yml is the default file, the plugin has never successfully loaded.

**Comment by nikosgram** [comment]
Hello @GamerMedic :)

Can you try the latest version and let me know if you can reproduce the issue?

Thanks :)
