### ISSUE TITLE
multiworld disabling

### ISSUE THREAD

**Issue by SirAltF4** [nikosgram/gringotts#63]
Hiya I am wondering if there is any way to disable Gringotts on certain worlds or disable the creation of vaults on certain worlds. I have a separate creative building world on my server and have realized you can just create a vault on this world and have infinite money. This is not ideal.
Is there any fix or any feature you could add in the config for this. 
many thanks 
AltF4

**Comment by Vidhin05** [comment]
Is there any way to do this?

**Comment by nikosgram** [comment]
Currently Gringotts doesn't support multi-worlds settings. 

I'll have a look on it and depends on how difficult will be to implement it, it will be added, or not :) 

Thanks.
