### ISSUE TITLE
/money pay doesn't work

### ISSUE THREAD

**Issue by kyle-vasilia** [nikosgram/gringotts#65]
the .transfer perm is given to all players - for some reason pay doesn't work at all even in all cases like when in the vault chest or in the inventory! When I do /money pay <x> Player - it says it has successfully sent 0.0 (My Currency) to them - I do not know why it does this. Has anyone fixed this? Or is it a permission issue?

**Comment by nikosgram** [comment]
It should be fixed on latest :) 9912a6a159e771075122fc32e13792f088c17917
